export enum ApiDocsDescriptions {
  // CHANGE_PASSWORD_FAIL = 'Occurs in case the new password does not meet the requirements.',
  // CHANGE_PASSWORD_OK = 'Returns the information of the user whose password changed.',
  // CREATE_USER_ROLE_FAIL = 'Occurs in case the user id or role id numbers do not correspond to any existing user or role respectively.',
  // CREATE_USER_ROLE_OK = 'Returns the user id and role id numbers associated.',
  // EMAIL_FAIL = 'Invalid email. Example: someone@mail.com',
  // PASSWORD_FAIL = 'The password must contain at least 6 characters including numbers, upper and lower case',
  // READ_ROLE_NAME_FAIL = 'Occurs in case the given name does not correspond to any existing role.',
  // REFRESH_TOKEN_FAIL = 'Could not decode jwt',
  // REFRESH_TOKEN_OK = 'Returns a new access token',
  // SAME_PASSWORD_FAIL = 'The confirmation password does not match the original password.',
  // DELETE_USER_FAIL = 'Occurs in case the given id number does not correspond to any registered user.',
  
  DELETE_USER_OK = 'Returns the information of the deleted user.',
  UPDATE_USER_FAIL = 'Occurs when a there is a problem updating the user.',
  UPDATE_USER_OK = 'Returns the information of the updated user.',
  READ_USER_FAIL = 'Occurs in case the given id number does not correspond to any registered user.',
  READ_USER_OK = 'Returns the information of the user.',
  READ_USERS_OK = 'Returns an array of registered users.',
  CREATE_USER_FAIL = 'Occurs in case the given user name is already registered.',
  CREATE_USER_OK = 'Returns the information of the created user.',
  DELETE_ROLE_OK = 'Returns the information of the deleted role.',
  UPDATE_ROLE_FAIL = 'Occurs when a there is a problem updating the role.',
  UPDATE_ROLE_OK = 'Returns the information of the updated role.',
  READ_ROLE_FAIL = 'Occurs in case the given id number does not correspond to any existing role.',
  READ_ROLE_OK = 'Returns the information of the role.',
  READ_ROLES_OK = 'Returns an array of existing user roles.',
  CREATE_ROLE_FAIL = 'Occurs in case the given combination of role name and type already exists.',
  CREATE_ROLE_OK = 'Returns the information of the created role.',
  UNAUTHORIZED = 'Occurs in case user is not authorized to request this endpoint.',
  LOGIN_OK = 'Returns the JWT token of the logged in user.',
}
